### PR TITLE
update to API 23

### PR DESCRIPTION
**Pull request by kusma**
The patch was picked up from [here](https://lists.freedesktop.org/archives/xorg-devel/2016-November/051848.html).

### CODE REVIEW

**Comment by digetx** [comment]
The patch is fine, however there are some of other generic fixes missed here. I've cherry-picked most of relevant fixes in my [fork](https://github.com/digetx/xf86-video-opentegra/commits/EXA-WIP-mess), but there is probably something new to pickup. Will have to revisit it.

**Comment by digetx** [comment]
We'll need DRI+EXA for mesa bring up. The older EXA implementation suffers from memory corruption. I've reworked it based on 2d code from NVIDIA folks and it worked reasonable well. But there was a bug in Xorg's EXA causing SW cursor to produce corruption when it is moving simultaneously with the underlying window (dragging it), I couldn't fix. I asked for help on #xorg and was told that EXA is obsolete and unmaintained, should switch to glamor. So the code in my fork has stuck in an intermediate state, it works but needs some cleanup.

**Comment by kusma** [comment]
If we require EXA for mesa-bringup, how can we use glamour to replace EXA?

**Comment by digetx** [comment]
We don't have to use glamor in the first place. We'll get the mesa+EXA to the state that it could handle glamor needs (they are fairly trivial, couple simple shaders IIRC) and then may switch to glamor.

**Pull request merged**
